version = 1

[merge]
automerge_label= "type: automerge"
require_automerge_label = true
delete_branch_on_merge = true
priority_merge_label= "type: automerge-priority"

[approve]
auto_approve_usernames = ["dependabot"]