export declare const fruits: {
    apple: string;
    apricot: string;
    avocado: string;
    banana: string;
    blackberry: string;
    'blood orange': string;
    blueberry: string;
    boysenberry: string;
    breadfruit: string;
    'buddhas hand citron': string;
    cantaloupe: string;
    clementine: string;
    'crab apple': string;
    currant: string;
    cherry: string;
    'custard apple': string;
    coconut: string;
    cranberry: string;
    date: string;
    dragonfruit: string;
    durian: string;
    elderberry: string;
    fig: string;
    gooseberry: string;
    grape: string;
    grapefruit: string;
    guava: string;
    'honeydew melon': string;
    jackfruit: string;
    kiwifruit: string;
    kumquat: string;
    lemon: string;
    lime: string;
    lychee: string;
    mandarine: string;
    mango: string;
    mangosteen: string;
    marionberry: string;
    nectarine: string;
    orange: string;
    papaya: string;
    passionfruit: string;
    peach: string;
    pear: string;
    persimmon: string;
    plantain: string;
    plum: string;
    pineapple: string;
    pluot: string;
    pomegranate: string;
    pomelo: string;
    quince: string;
    raspberry: string;
    rambutan: string;
    soursop: string;
    starfruit: string;
    strawberry: string;
    tamarind: string;
    tangelo: string;
    tangerine: string;
    'ugli fruit': string;
    watermelon: string;
    'white currant': string;
    yuzu: string;
};
export declare const veggies: {
    celery: string;
    onion: string;
    pepper: string;
};
