// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string
  content: string
  modal: string
  modalContainer: string
  overlay: string
  title: string
}
export const cssExports: CssExports
export default cssExports
