version: 1
update_configs:
  # Keep js modules up to date, batching pull requests weekly
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "weekly"
    # Apply dependencies label to PRs
    default_labels:
      - "type: dependencies"
      - "type: automerge"
    allowed_updates:
      # allow updates to development dependencies
      - match:
          dependency_type: "development"
          update_type: "all"
      # security patches for all
      - match:
          dependency_type: "all"
          update_type: "security"
    ignored_updates:
      # don't upgrade react packages beyond major.minor
      - match:
          dependency_name: "react"
          version_requirement: "^16.11.0"
      - match:
          dependency_name: "react-dom"
          version_requirement: "^16.11.0"
      - match:
          dependency_name: "@types/react"
          version_requirement: "^16.10.0"
      - match:
          dependency_name: "@types/react-dom"
          version_requirement: "^16.10.0"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
