name: Deploy Storybook

on:
  push:
    tags:
      - '[1-9].*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-storybook:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    name: Deploy Storybook
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    steps:
      - name: Check out repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Set up node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      - name: Deploy 🚀
        uses: bitovi/github-actions-storybook-to-github-pages@b75ece8f984a32b2adb322065d7a8a2cc8db2d52 # v1.0.3
        with:
          install_command: npm ci
          build_command: npm run build-storybook
          path: storybook-static
          checkout: false
