name: Package release

on:
  pull_request:
    types: 
      - closed
    branches: 
      - main

jobs:
  package-release:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.head_ref, 'release-')
      && github.event.pull_request.merged

    strategy:
      fail-fast: false

    steps: 
      - name: Checkout out repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Set up Node
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version-file: '.node-version'
          cache: 'npm'

      # The npm cache is not node_modules
      - name: Install Dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Package library
        # https://docs.npmjs.com/cli/commands/npm-pack
        run: npm pack

      - name: Upload package
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          path: trussworks-react-uswds-*.tgz
          if-no-files-found: error
          retention-days: 5
